version: '3.8'

services:
    presenca-db:
        image: postgres:15
        container_name: presenca-db
        environment:
            POSTGRES_USER: dudu_adm
            POSTGRES_PASSWORD: morango
            POSTGRES_DB: presenca_database
        ports:
            - "5438:5432"
        volumes:
            - presenca_data:/var/lib/postgresql/data

    presenca-service:
        build: .
        container_name: presenca-service
        environment:
            PSQL_HOST: presenca-db
            PSQL_PORT: 5432
            PSQL_NAME: presenca_database
            PSQL_USER: dudu_adm
            PSQL_PASS: morango
        ports:
            - "3005:3005"
        depends_on:
            - presenca-db

volumes:
    presenca_data:
