version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_soa
    restart: always
    environment:
      POSTGRES_DB: hub_academico
      POSTGRES_USER: dudu_adm
      POSTGRES_PASSWORD: morango
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user_service
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  palestra-service:
    build: ./palestra-service
    container_name: palestra_service
    restart: always
    env_file:
      - ./palestra-service/.env
    ports:
      - "3333:3002"
    depends_on:
      - db

volumes:
  pgdata:
