services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: hub_academico
      POSTGRES_USER: dudu_adm
      POSTGRES_PASSWORD: morango
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5424:5432"
    networks:
      - soa-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
    depends_on:
      - db
    networks:
      - soa-network

  palestra-service:
    build:
      context: ./palestra-service
      dockerfile: Dockerfile
    container_name: palestra-service
    ports:
      - "3002:3002"
    env_file:
      - ./palestra-service/.env
    depends_on:
      - db
    networks:
      - soa-network

  esb-service:
    build:
      context: ./esb-service
      dockerfile: Dockerfile
    container_name: esb-service
    ports:
      - "8000:8000"
    networks:
      - soa-network

volumes:
  postgres_data:

networks:
  soa-network:
    driver: bridge
