version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_monolito
    restart: always
    environment:
      POSTGRES_DB: path_architecture_database
      POSTGRES_USER: dudu_adm
      POSTGRES_PASSWORD: morango
    ports:
      - "5469:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: monolito_app
    depends_on:
      - db
    environment:
      PSQL_HOST: db
      PSQL_PORT: 5432
      PSQL_NAME: path_architecture_database
      PSQL_USER: dudu_adm
      PSQL_PASS: morango
    ports:
      - "3333:3333"
    command: sh -c "node server.js"

volumes:
  postgres_data:
